create table t ( id int , t_name char (500));
create table d (id int,d_name char(500));
insert into t values(1,'');
insert into t values(2,'');
insert into t values(3,'');
insert into t values(4,'');
insert into t values(5,'');
insert into t values(6,'');
insert into t values(7,'');
insert into t values(8,'');
insert into t values(9,'');
insert into t values(10,'');
insert into t values(11,'');
insert into t values(12,'');
insert into t values(13,'');
insert into t values(14,'');
insert into t values(15,'');
insert into t values(16,'');
insert into d values(1,'');
insert into d values(2,'');
insert into d values(3,'');
insert into d values(4,'');
insert into d values(5,'');
insert into d values(6,'');
insert into d values(7,'');
insert into d values(8,'');
insert into d values(9,'');
insert into d values(10,'');
insert into d values(11,'');
insert into d values(12,'');
insert into d values(13,'');
insert into d values(14,'');
insert into d values(15,'');
insert into d values(16,'');
insert into d values(17,'');
insert into d values(18,'');
insert into d values(19,'');
insert into d values(20,'');
insert into d values(21,'');
insert into d values(22,'');
insert into d values(23,'');
insert into d values(24,'');
select d.id,t.id from t,d;
select t.id,t_name,d_name from t,d where t.id = d.id;
drop table t;
drop table d;